// <auto-generated />
using LibrarySystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LämnaInEntity.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260512044843_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibrarySystem.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jk@example.com",
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 2,
                            Email = "orwell@example.com",
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = 3,
                            Email = "austen@example.com",
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = 4,
                            Email = "twain@example.com",
                            Name = "Mark Twain"
                        },
                        new
                        {
                            Id = 5,
                            Email = "hemingway@example.com",
                            Name = "Ernest Hemingway"
                        },
                        new
                        {
                            Id = 6,
                            Email = "fitzgerald@example.com",
                            Name = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            Id = 7,
                            Email = "christie@example.com",
                            Name = "Agatha Christie"
                        },
                        new
                        {
                            Id = 8,
                            Email = "tolkien@example.com",
                            Name = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = 9,
                            Email = "sking@example.com",
                            Name = "Stephen King"
                        },
                        new
                        {
                            Id = 10,
                            Email = "murakami@example.com",
                            Name = "Haruki Murakami"
                        },
                        new
                        {
                            Id = 11,
                            Email = "tolstoy@example.com",
                            Name = "Leo Tolstoy"
                        },
                        new
                        {
                            Id = 12,
                            Email = "vwoolf@example.com",
                            Name = "Virginia Woolf"
                        });
                });

            modelBuilder.Entity("LibrarySystem.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            ISBN = "100001",
                            PublishedYear = 1997,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            ISBN = "100002",
                            PublishedYear = 1998,
                            Title = "Harry Potter and the Chamber of Secrets"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            ISBN = "100003",
                            PublishedYear = 1999,
                            Title = "Harry Potter and the Prisoner of Azkaban"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            ISBN = "100004",
                            PublishedYear = 2000,
                            Title = "Harry Potter and the Goblet of Fire"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            ISBN = "100005",
                            PublishedYear = 2003,
                            Title = "Harry Potter and the Order of the Phoenix"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            ISBN = "100006",
                            PublishedYear = 2005,
                            Title = "Harry Potter and the Half-Blood Prince"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            ISBN = "100007",
                            PublishedYear = 2007,
                            Title = "Harry Potter and the Deathly Hallows"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            ISBN = "200001",
                            PublishedYear = 1949,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 2,
                            ISBN = "200002",
                            PublishedYear = 1945,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 3,
                            ISBN = "200003",
                            PublishedYear = 1932,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 4,
                            ISBN = "200004",
                            PublishedYear = 1953,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 5,
                            ISBN = "200005",
                            PublishedYear = 1985,
                            Title = "The Handmaid's Tale"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 6,
                            ISBN = "300001",
                            PublishedYear = 1937,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 6,
                            ISBN = "300002",
                            PublishedYear = 1954,
                            Title = "The Lord of the Rings: Fellowship"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 6,
                            ISBN = "300003",
                            PublishedYear = 1954,
                            Title = "The Two Towers"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 6,
                            ISBN = "300004",
                            PublishedYear = 1955,
                            Title = "The Return of the King"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 7,
                            ISBN = "400001",
                            PublishedYear = 1965,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 7,
                            ISBN = "400002",
                            PublishedYear = 1969,
                            Title = "Dune Messiah"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 7,
                            ISBN = "400003",
                            PublishedYear = 1976,
                            Title = "Children of Dune"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 7,
                            ISBN = "400004",
                            PublishedYear = 1981,
                            Title = "God Emperor of Dune"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 8,
                            ISBN = "500001",
                            PublishedYear = 2003,
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 8,
                            ISBN = "500002",
                            PublishedYear = 2000,
                            Title = "Angels & Demons"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 8,
                            ISBN = "500003",
                            PublishedYear = 2013,
                            Title = "Inferno"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 8,
                            ISBN = "500004",
                            PublishedYear = 2017,
                            Title = "Origin"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 9,
                            ISBN = "600001",
                            PublishedYear = 1977,
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 9,
                            ISBN = "600002",
                            PublishedYear = 1986,
                            Title = "It"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 9,
                            ISBN = "600003",
                            PublishedYear = 1987,
                            Title = "Misery"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 9,
                            ISBN = "600004",
                            PublishedYear = 1974,
                            Title = "Carrie"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 10,
                            ISBN = "700001",
                            PublishedYear = 1988,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 10,
                            ISBN = "700002",
                            PublishedYear = 1990,
                            Title = "Brida"
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 10,
                            ISBN = "700003",
                            PublishedYear = 1998,
                            Title = "Veronika Decides to Die"
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 10,
                            ISBN = "700004",
                            PublishedYear = 2003,
                            Title = "Eleven Minutes"
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 11,
                            ISBN = "800001",
                            PublishedYear = 1887,
                            Title = "Sherlock Holmes: Study in Scarlet"
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 11,
                            ISBN = "800002",
                            PublishedYear = 1890,
                            Title = "Sherlock Holmes: Sign of Four"
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 11,
                            ISBN = "800003",
                            PublishedYear = 1902,
                            Title = "Sherlock Holmes: Hound of Baskervilles"
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 11,
                            ISBN = "800004",
                            PublishedYear = 1912,
                            Title = "Lost World"
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 12,
                            ISBN = "900001",
                            PublishedYear = 2019,
                            Title = "The Silent Patient"
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 12,
                            ISBN = "900002",
                            PublishedYear = 2021,
                            Title = "The Maidens"
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 12,
                            ISBN = "900003",
                            PublishedYear = 2024,
                            Title = "The Fury"
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 12,
                            ISBN = "900004",
                            PublishedYear = 2022,
                            Title = "Mystery of the Mind"
                        });
                });

            modelBuilder.Entity("LibrarySystem.Models.BookCategory", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 11,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 17,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 18,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 21,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 22,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 37,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 38,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 25,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 26,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 28,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 13,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 14,
                            CategoryId = 1
                        });
                });

            modelBuilder.Entity("LibrarySystem.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dystopian"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("LibrarySystem.Models.Book", b =>
                {
                    b.HasOne("LibrarySystem.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LibrarySystem.Models.BookCategory", b =>
                {
                    b.HasOne("LibrarySystem.Models.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibrarySystem.Models.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibrarySystem.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibrarySystem.Models.Book", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("LibrarySystem.Models.Category", b =>
                {
                    b.Navigation("BookCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
